pub const JOB_TITLES: [&str; 27] = [
    "Software Developer",
    "Backend Developer",
    "Frontend Developer",
    "Fullstack Developer",
    "Ruby Developer",
    "Rust Developer",
    "Javascript Developer",
    "React Developer",
    "Mobile Developer",
    "Flutter Developer",
    "Software Engineer",
    "Backend Engineer",
    "Frontend Engineer",
    "Fullstack Engineer",
    "Ruby Engineer",
    "Rust Engineer",
    "Javascript Engineer",
    "React Engineer",
    "Mobile Engineer",
    "Flutter Engineer",
    "Programmer",
    "Coder",
    "Loving Husband",
    "Amateur Gardener",
    "Aikidoka",
    "Iaijutsuka",
    "Human Being",
];
